@startuml

title __PIZZERIA's Class Diagram__\n

  namespace observer {
    class observer.CourseRecord {
    }
  }
  

  namespace observer {
    class observer.LayoutConstants {
    }
  }
  

  namespace observer {
    namespace nonpattern {
      class observer.nonpattern.CourseViewer {
      }
    }
  }
  

  namespace observer {
    namespace pattern {
      class observer.pattern.BarChartObserver {
      }
    }
  }
  

  namespace observer {
    namespace pattern {
      class observer.pattern.CourseController {
      }
    }
  }
  

  namespace observer {
    namespace pattern {
      class observer.pattern.CourseData {
      }
    }
  }
  

  namespace observer {
    namespace pattern {
      abstract class observer.pattern.Observable {
      }
    }
  }
  

  namespace observer {
    namespace pattern {
      interface observer.pattern.Observer {
      }
    }
  }
  

  observer.nonpattern.CourseViewer .up.|> java.awt.event.ActionListener
  observer.nonpattern.CourseViewer .up.|> javax.swing.event.ChangeListener
  observer.nonpattern.CourseViewer -up-|> javax.swing.JFrame
  observer.pattern.BarChartObserver .up.|> observer.pattern.Observer
  observer.pattern.BarChartObserver -up-|> javax.swing.JPanel
  observer.pattern.CourseController .up.|> java.awt.event.ActionListener
  observer.pattern.CourseController .up.|> javax.swing.event.ChangeListener
  observer.pattern.CourseController .up.|> observer.pattern.Observer
  observer.pattern.CourseController -up-|> javax.swing.JPanel
  observer.pattern.CourseController o-- observer.pattern.CourseData : courseData
  observer.pattern.CourseData -up-|> observer.pattern.Observable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
